# Generated by Django 4.0.2 on 2022-09-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name_plural': 'Units'},
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(),
        ),
    ]
