# Generated by Django 4.0.2 on 2022-09-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_units_options_alter_date_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
