# Generated by Django 4.0.2 on 2022-10-03 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_item_supplier_alter_item_units'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Units',
        ),
    ]
