# Generated by Django 4.0.2 on 2022-10-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_delete_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('projected_cost', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('projected_end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
